if [ -f "${HOME}/.Xresources"]; then
    xrdb -merge "${HOME}/.Xresources"
fi

feh --bg-scale "${HOME}/Pictures/wall/wallpaper.png" --no-fehbg &
xset -b &
xset s off -dpms &
amixer sset Master 0 &
numlockx &
greenclip daemon &
exec xmonad
