services:
  portainer:
    container_name: portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    image: portainer/portainer
    ports:
    - 8000:8000
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
version: '3'