if [ -f "${HOME}/.Xresources" ] ; then
    xrdb -merge "${HOME}/.Xresources"
fi

export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export GTK_SCALE=2
export GTK_DPI_SCALE=0.5
sleep 1 & ${HOME}/.config/wm_script/startup.sh
exec awesome
